# Use postgres/example user/password credentials
version: '3.9'

services:

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_PASSWORD: 123456
      MARIADB_USER: furry
      MARIADB_DATABASE: maria
      MARIADB_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"